### ISSUE TITLE
Se över och ta notis över formuleringarna på test frågor

### ISSUE THREAD

**Issue by Mercenaress** [ZoCom-utbildning/folkans-it-utbildningar#461]
Ta notis på formuleringar av test frågor och svar som ser konstiga ut.
Ta med till Alvaro och/eller Måns för omformulering.

**Comment by fabiolapoblete** [comment]
Fått ok av Alvaro på de nya texterna. 
Avvaktar med att lägga in i databasen tills vi fått ok från Johan också.

**Comment by fabiolapoblete** [comment]
Fått ok av Christoffer att uppdatera databasen.

**Comment by fabiolapoblete** [comment]
Databas updaterad enligt följande:

Fråga 4: 
"Jag planerar för genom att dela in uppgiften i faser. När jag har en bra planering sätter jag igång, aldrig innan."

🍀 Ny: "Jag planerar genom att dela upp uppgiften i faser.  När jag har en bra planering sätter jag igång, aldrig innan"

Fråga 6: 
"Jag sätter mig ned, försöker slappna av och försöker strukturera upp och koda av uppgiften för att få en tydligare bild av vad som förväntas av mig."

🍀 Ny: "Jag sätter mig ner, försöker slappna av och bryter ner uppgiften för att få en klarare uppfattning om vad som förväntas av mig."
